Feature: report issues as discovered instead of buffering
godaddy/tartufo pull request #227
Opened 2021-10-13 14:52 UTC by rbailey-godaddy

This is a reimplementation of PR #108 which streams output (including JSON).

To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [x] Changelog entry
* [x] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [x] Yes (backward compatible)
* [ ] No (breaking changes)

## Issue Linking

## What's new?

Issues are now written to the console as soon as they are detected, while the scan is in progress, instead of buffering all of them and reporting only when the scan has completed. This is generally backward compatible:
* A user who starts a scan and walks away, returning only after the scan has completed, will not detect any changes in behavior.
* A caller who references only the `issues` property (and not the `scan()` method) will see no changes in behavior.
* A caller who references only the `scan()` method (and not the `issues` property) will see no changes in behavior, although the method is now a generator that returns issues in succession rather than a function which returns a list. A caller who does `len(scanner.scan())` (or anything else that assumes the result is a list) should use `scanner.issues` (which is a list) instead.
* A caller using both `scan()` and `issues`, where _all_ `scan()` references occur before _all_ `issues` references, will see no changes in behavior.

These cases are not backward compatible: 
* A caller who invokes `scan()` multiple times, expecting to see the scan re-run each time, will observe different behavior. The first series of invocations identifies (and caches) issues, but subsequent invocations re-use the cached issues instead of actually rescanning the target. It looks the same (if you allow for generator vs. list) but you are not actually doing repeated scans.
* A caller who references `issues` and then calls `scan()` will see that the `scan()` call now will iterate over the cached issue list instead of rescanning. Once the caller has referenced the `issues` property, any subsequent `scan()` calls should be replaced with references to `issues`.
* In particular, consuming some (partial) number of issues from `scan()` and then referencing `issues` will return the full list of issues, but cause `scan()` to generate from the cached issues list, meaning that the initial issues will appear to be duplicated. The caller should either use `issues` exclusively, or ensure all references to `issues` occur after all calls to `scan()`.

This change was accomplished using the following strategy:
* `ScannerBase` methods which previously appended to the `_issues` member have been converted to generators which yield individual issues; the lowest-level methods still append to `_issues` (so as to cache a record of all issues) in addition to yielding the issue. In particular, `scan()` is now a generator.
* A new `_completed` member (and matching `completed` property) track whether a scan is still in progress (i.e. whether or not the `scan()` generator is exhausted); this is initially `False` and set to `True` by `scan()` when it finally exits.
* The `issues` property now tests to see if the scan is still in progress, and forcibly drains the generator if needed prior to returning the issues list (which otherwise could be incomplete).
* `echo_output()` now loops on `scan()` instead of `issues` in order to obtain issues individually as they are detected, allowing output to be produced as soon as it is encountered; some code reordering was performed to ensure no references to `issues` occur before all references to `scan()` have been made.
* The output blocks of `echo_output()` were refactored to output individual issues instead of consolidating output to a single large result at the end -- in the most complicated of these, JSON output is handled by generating it in pieces: an initial part, a part for each issue, and a terminal part -- the resulting output is unchanged, but it now appears incrementally;
* Unit testing generally required only minor fixups. The JSON-related unit tests were modified to perform end-to-end validation of the output stream to ensure we're generating valid JSON that correctly reflects the original input data.

2021-10-13 22:28 UTC, sushantmimani approved these changes
LGTM 🦅

2021-10-25 21:48 UTC, tarkatronic requested changes
Some of this is probably just a bit of pontification (specifically the thread safety stuff), but I do want to be sure we don't add more side-effects where they did not previously exist.

2021-10-25 21:48 UTC, tarkatronic commented on tartufo/scanner.py
> +            list(self.scan())
I'm not quite sure about this method of handling this. I'm almost starting to think it's gotta be more of a state machine. Imagine, if you will:

* I am a 3rd party developer using `tartufo` as a library
* In my program, I spin up a new thread to run `scanner.scan()`.
* In my main thread, I have code along the lines of:
    ```python
    while not scanner.issues:
        print("Waiting for scan to complete...")
        time.sleep(5)
    ```
* It seems that this is now going to cause 2 concurrent scans to run. And that isn't ideal.

Although I suppose this sticks with the pre-existing functionality. So maybe that's not the worst thing, and we re-visit the concurrency model/safety at a later date.

2021-10-25 21:48 UTC, tarkatronic commented on tartufo/scanner.py
> +                    self._issues.append(issue)
Let's try to keep this append at a higher level if we can. It should be possible to yield here, and maintain the generator functionality, but still only append the issues once at a higher level. That way there are no side effects on these lower-level functions.

2021-10-25 21:48 UTC, tarkatronic commented on tartufo/scanner.py
> +                        self._issues.append(issue)
Same on this append here.

2021-10-25 21:48 UTC, tarkatronic commented on tests/test_cli.py
> +        mock_scanner.return_value.issue_count = 0
Pretty sure this attribute went away 😄

2021-10-25 22:04 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +            list(self.scan())
Only 1 scan runs. Suppose we will (eventually) return issues 1, 2, 3, ... 100.

Your scanner thread begins consuming `scanner.scan()` issues...

If your main thread starts the while loop *AFTER* the scanner thread finishes iterating:

* The scanner thread sees issues 1 - 100 in order
* The main thread exits the loop immediately

If your main thread starts the while loop *DURING* the scanner thread iteration (say just after issue 50 is viewed):

* The scanner thread sees issues 1-50 in order (before the main thread stuck its oar in the water), and then sees nothing more (because all subsequent issues were drained by `.issues`) and then, if it were called again, would return issues 1-100 in order (obtained by replaying `._issues`)...
* The main thread exits the loop immediately (after a delay during which issues 51-100 are enumerated)

If your main thread starts the while loop *BEFORE* the scanner thread starts iterating:

* The scanner thread sees issues 1-100 in order (returned by replaying `._issues`)
* The main thread exits the loop immediately (after a longer delay during which issues 1-100 are enumerated)

The only multithread wackiness would be in the fine print of the "DURING" case. Both are yielding issues from the low-level generators, which append to `._issues` just prior to yielding individual issues. So the question is, are generators and list append operations intrinsically thread-safe?

2021-10-25 22:07 UTC, rbailey-godaddy commented on tests/test_cli.py
> +        mock_scanner.return_value.issue_count = 0
It did. I removed this one and a few of its buddies in other tests too.

2021-10-25 23:14 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +                    self._issues.append(issue)
This (and the next) annoy me to hoist because I need to introduce loops inside `scan()`, which seems less clean to me, but I understand the issue of reducing side-effects. A commit with this change has been added.

2021-10-25 23:14 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +                        self._issues.append(issue)
Ditto.

2021-10-26 14:14 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +            list(self.scan())
The latest commit uses explicit locking to ensure all `scan()` invocations execute sequentially.

2021-10-26 16:55 UTC, tarkatronic commented on tartufo/scanner.py
> +                    self._issues.append(issue)
FWIW I agree, it's a tough balance and either way there is compromise to be made. I just tend to err on the side of reducing/condensing side effects in the hopes of maintaining a higher level of determinism and idempotency.

Thanks for updating this!

2021-10-26 16:58 UTC, tarkatronic commented on tartufo/scanner.py
> +            list(self.scan())
>  So the question is, are generators and list append operations intrinsically thread-safe?

Probably not 😅 This was largely me thinking out loud, and like I said we'll probably need to revisit the concurrency model later once we have an actual real use case. For now though, I think this will make for a great effort at correctness!

2021-10-26 17:02 UTC, tarkatronic approved these changes
Thanks for putting in all the hard work on this @rbailey-godaddy!

2021-10-26 17:15 UTC, sushantmimani approved these changes
LGTM 🦅

2021-10-26 17:26 UTC, merged