Switch to Pygit2
godaddy/tartufo pull request #233
Opened 2021-10-19 22:49 UTC by sushantmimani

To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [x] Tests (if applicable)
* [ ] Documentation (if applicable)
* [ ] Changelog entry
* [x] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [x] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [ ] Yes (backward compatible)
* [x] No (breaking changes)
In its current version, this PR will flag findings for renamed files even if the findings in the new file(after rename) have been excluded from Tartufo.

## What's new?
This is the first PR in a series of PRs aimed at re-implementing #122. Current status:
- scan-remote-repo runs successfully
- scan-local-repo runs successfully
- pre-commit runs successfully
- All unit tests pass
- `--max-depth` option is unimplemented
- file renames are not tracked so extra findings ( which might have exclusions for the new file path) are generated

2021-10-20 14:00 UTC, rbailey-godaddy reviewed
Looking pretty good, although I bet it was a lot harder to come up with the changes than it was to read them. I noted one point where a message was dropped in the transformation -- I'm guessing that is unintentional because the look-and-feel appears unchanged everywhere else.

2021-10-20 14:00 UTC, rbailey-godaddy commented on tartufo/scanner.py
> -            self.logger.info("Scanning branch: %s", branch)
Did this get dropped intentionally, or should it be reinserted between L633 and L634?

2021-10-21 00:02 UTC, sushantmimani commented on tartufo/scanner.py
> -            self.logger.info("Scanning branch: %s", branch)
I dropped it accidentally. Added back now.

2021-10-25 23:20 UTC, emayuri-godaddy approved these changes
LGTM!

2021-10-26 17:50 UTC, rbailey-godaddy approved these changes
LGTM. I didn't see anything weird at this point, and I trust the unit tests more than my deductive abilities in this area. ;-)

2021-10-26 18:13 UTC, tarkatronic requested changes
Just one small thing here and I think we're good for an MVP on this change.

2021-10-26 18:13 UTC, tarkatronic commented on tartufo/scanner.py
> +                    continue
What is this here for? What would a commit with no parents indicate?

Also we should probably add a debug log here.

2021-10-26 19:42 UTC, tarkatronic approved these changes
This will be a great starting point for a fast new tartufo! Thanks for all the work @jgowdy, @sushantmimani, and @emayuri-godaddy!

2021-10-26 20:09 UTC, merged