Explicitly state version for removal of deprecated options
godaddy/tartufo pull request #362
Opened 2022-06-30 18:48 UTC by sushantmimani

To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [ ] Changelog entry
* [x] A full explanation here in the PR description of the work done

Update deprecation warnings to state that all deprecated options will be remove from Tartufo 4.x

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [x] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [x] Yes (backward compatible)
* [ ] No (breaking changes)

2022-06-30 18:56 UTC, rbailey-godaddy requested changes
Editorial wordsmithing.

2022-06-30 18:56 UTC, rbailey-godaddy commented on tartufo/config.py
> +            "in Tartufo 4.x. You should be using the 'rule-patterns' config "
```suggestion
            "in tartufo 4.x. Please use the 'rule-patterns' config "
```
I checked usage in tartufo.readthedocs.io and the canonical name appears to be all lowercase.

2022-06-30 18:56 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +                "Use --entropy-sensitivity instead.",
```suggestion
                "--hex-entropy-score is deprecated and will be removed in tartufo 4.x. "
                "Please use --entropy-sensitivity instead.",
```

2022-06-30 18:56 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +                "Use --entropy-sensitivity instead.",
```suggestion
                "--b64-entropy-score is deprecated and will be removed in tartufo 4.x. "
                "Please use --entropy-sensitivity instead.",
```

2022-06-30 18:56 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +                    "= ['inclusion pattern'] has been deprecated and will be removed in Tartufo 4.x. "
```suggestion
                    "= ['inclusion pattern'] has been deprecated and will be removed in tartufo 4.x. "
```

2022-06-30 18:56 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +                    "= ['exclusion pattern'] has been deprecated and will be removed in Tartufo 4.x. "
```suggestion
                    "= ['exclusion pattern'] has been deprecated and will be removed in tartufo 4.x. "
```

2022-06-30 18:56 UTC, rbailey-godaddy commented on tartufo/scanner.py
> +                    "be removed in Tartufo 4.x. Please make sure to update your exclude-signatures configuration to "
```suggestion
                    "be removed in tartufo 4.x. Please update your exclude-signatures configuration to "
```

2022-06-30 19:06 UTC, rbailey-godaddy approved these changes

2022-07-05 18:26 UTC, emayuri-godaddy approved these changes

2022-07-05 20:08 UTC, merged