feat(output): add report output format
godaddy/tartufo pull request #399
Opened 2022-11-10 19:14 UTC by dclayton-godaddy

To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [ ] Changelog entry
* [ ] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [ ] Yes (backward compatible)
* [ ] No (breaking changes)

## Issue Linking

## What's new?
-

2022-11-11 23:35 UTC, mgaspar-godaddy commented
I like it. This would help greatly when someone needs to submit their scan results to someone else to be able to quickly and easily know what each exclusions is for and greatly speed up any review process in place.

2022-11-15 17:08 UTC, sjacoby-godaddy approved these changes
looks good

2022-11-15 18:28 UTC, sushantmimani commented on pyproject.toml
> +python = "^3.7"
It'll be preferable if we keep the "drop support for 3.6" changes out of this PR, unless there's something that necessitates this change in this PR.

2022-11-15 18:28 UTC, sushantmimani requested changes
"Drop support for 3.6" should be a separate PR.

2022-11-15 19:02 UTC, schoi-godaddy reviewed
Like the new format, ty.

2022-11-15 19:02 UTC, schoi-godaddy commented on tartufo/cli.py
> +            types.OutputFormat.Report.value,
Could we add this to below help text as well please?

2022-11-21 19:29 UTC, closed without merging