bump GitPyhton
godaddy/tartufo pull request #448
Opened 2023-02-27 20:41 UTC by vjohnson1-godaddy

Bump the version of `GitPython` to avoid [this security vulnerability](https://github.com/advisories/GHSA-hcpj-qp55-gfph)

## PR Type
What kind of change does this PR introduce?

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility
* [x] Yes (backward compatible)
* [ ] No (breaking changes)

## Issue Linking
- https://godaddy-corp.atlassian.net/browse/ML-6603

## What's new?
- `GitPython` version bumped from `3.1.29` to `3.1.30`
- Lockfile updated

2023-02-27 20:54 UTC, emayuri-godaddy commented
@vjohnson1-godaddy Thank you for the PR. Can we please have the [CHANGELOG.md](https://github.com/godaddy/tartufo/blob/main/CHANGELOG.md) updated for this change?

2023-02-27 21:02 UTC, rbailey-godaddy requested changes
Sorry to give you more work; please revert the version number (that's done only during release process). You can use "vX.X.X" as a placeholder in the CHANGELOG.md -- that gets fixed at release time too.

2023-02-28 00:37 UTC, rbailey-godaddy approved these changes

2023-02-28 17:00 UTC, sushantmimani approved these changes

2023-02-28 17:40 UTC, emayuri-godaddy approved these changes

2023-03-01 18:05 UTC, merged