Add a doc for example cleanup process walkthrough
godaddy/tartufo pull request #49
Opened 2020-04-20 19:26 UTC by sjacoby-godaddy

2020-04-21 20:03 UTC, mxhenry-godaddy approved these changes

2020-04-21 20:31 UTC, tarkatronic requested changes
@sjacoby-godaddy Thanks for adding this! The "what to do next" is something which we've really needed here.

Before we get this merged, I want to work through a bit of cleanup to make this as easy to manage as possible for our users. Unfortunately I haven't yet gotten around to documenting any style guidelines for writing documentation. For a start, I would encourage two things:

1. If you have access to MacOS X or Linux (including WSL), run: `tox -e docs`. This will build a local copy of the documentation, as it will appear on the final Read The Docs site, under the `docs/build/html/` folder. This file you have created will be named `examplecleanup.html`.
2. Browse around the rest of the documentation to get a feel for the tone of writing. As much as possible, it would be nice to maintain a consistent writing tone to any readers. This should make the docs easier to follow. I suggest this because I would love to see a bit more verbosity on what this document is covering, why, and how.

The most immediate concern I have right now is just cleaning up warnings produced from step 1 above. Those currently look like:
```
docs/source/examplecleanup.rst:2: WARNING: Title underline too short.

tartufo Full Example
=======
docs/source/examplecleanup.rst:5: WARNING: Title underline too short.

End-to-End Example
-----------

checking consistency... docs/source/examplecleanup.rst: WARNING: document isn't included in any toctree
docs/source/examplecleanup.rst:11: WARNING: Could not lex literal_block as "console". Highlighting skipped.
docs/source/examplecleanup.rst:43: WARNING: Could not lex literal_block as "console". Highlighting skipped.
docs/source/examplecleanup.rst:86: WARNING: Could not lex literal_block as "console". Highlighting skipped.
```
Most of these should be fairly self-explanatory. The `toctree` one may not be immediately clear though. What this boils down to is that you need to add a reference to the document under the `toctree` directive at the bottom of `index.rst`.

2020-04-23 21:39 UTC, tarkatronic requested changes
This is great! Just a few more small tweaks -- almost there!

I love that this has become more of a narrative, as opposed to a list of steps.

2020-04-23 21:39 UTC, tarkatronic commented on docs/source/examplecleanup.rst
> +
Can you add something up top here, along the lines of:

> In order to follow along with this guide, you will also want to install the `BFG` tool from ...

Just talking about BFG without any kind of introduction is a bit off-putting.

2020-04-23 21:39 UTC, tarkatronic commented on docs/source/examplecleanup.rst
> +An End-to-End example walkthrough of tartufo cleanup
Could you expand this a little bit? Just saying `tartufo cleanup` I think begs the question, "How does this differ from `tartufo --cleanup`?"

Maybe saying something like, "Now that you have found secrets in your repo, what do you do with that information?" ...but, you know, maybe a bit better wording than that. :smile:

2020-04-23 21:39 UTC, tarkatronic commented on docs/source/index.rst
> +.. _usage:
This shouldn't be here; this makes the link below point up here, instead of to the `usage` page.

2020-04-23 21:39 UTC, tarkatronic commented on docs/source/index.rst
> +   For more detail on usage and options, see :ref:`Link title <usage>`.
I'm not sure this is quite what you intended to do... This now looks like:
> For more detail on usage and options, see Link title.

2020-04-23 21:39 UTC, tarkatronic commented on docs/source/usage.rst
> +++++++++++++++++++++++
Thanks for fixing this!

2020-04-23 21:39 UTC, tarkatronic commented on docs/source/usage.rst
> +.. _examplecleanup:
Similar to the `.. _usage:` on the index, this shouldn't be here; it turns this into an anchor, so that the link below simply points here.

2020-04-23 21:39 UTC, tarkatronic commented on docs/source/usage.rst
> +Would you like to know more? See :ref:`Link title <examplecleanup>`.
Same as on the index, this now looks like:
> Would you like to know more? See Link title.

2020-04-23 22:19 UTC, tarkatronic approved these changes
:boom: :microphone: :droplet:

2020-04-23 22:21 UTC, merged